### ISSUE TITLE
Light group never gets discovered

### ISSUE THREAD

**Issue by jmelby70** [rudders/homebridge-platform-wemo#29]
I have a Wemo Link with 2 separate light groups with 2 bulbs each. One of the groups is always discovered and works fine, but the other group never is discovered. No matter how many times I restart and change the timeout (I set it as high as 120), it never finds one of the groups (always the same one). If I split up the group in the Wemo app, it can discover and control each of the bulbs separately just fine, but not when they are grouped.

I also just updated to 0.6.5, but now with the homekit_safe setting to 0, it crashes after the timeout anyway because I have the total # of devices set to include the bulb group that doesn't get discovered. So, it looks like that setting to ignore if it doesn't find everything is broken in the latest release.

**Comment by rudders** [comment]
1. I have don't no testing on groups so I'll need to investigate.
2. Can you post the relevant part of you config.json and I'll address the homekitsafe issue for you

**Comment by jmelby70** [comment]
Here's my platform config:
"platforms": [
        {
          "platform": "BelkinWeMo",
          "name": "WeMo Platform",
          "expected_accessories": "12",
          "timeout" : "120",
          "no_motion_timer": "60",
          "homekit_safe": "0"
        }
    ]

I have 12 accessories (counting the light groups as 1 each), but it only ever finds 11 as I noted. Even with the homekit_safe setting as 0, it crashes after the timeout with the expected error as if the setting was 1:

Error: homebridge-wemo-platform has intentially bought down HomeBridge - please restart - sorry but it's your HomeKit configuration we're protecting!
    at null._onTimeout (/usr/local/lib/node_modules/homebridge-platform-wemo/index.js:109:27)
    at Timer.listOnTimeout (timers.js:92:15)

Thanks for taking a look!

**Comment by rudders** [comment]
could you try the following please (i.e. remove the quotes from around the 0)
you could also try "false" instead of "0" or 0 
what platform/OS are you on btw?
```
{
         "platform": "BelkinWeMo",
         "name": "WeMo Platform",
         "expected_accessories": "12",
         "timeout" : "120",
         "no_motion_timer": "60",
         "homekit_safe": 0
       }
```

**Comment by jmelby70** [comment]
I tried both removing the quotes around the 0 and setting to just false (with quotes and without), but it still behaves the same. This isn't such a big deal because I know I can just set the expected value to 11, but just wanted to let you know it's not working as you intend.

Thanks again!

**Comment by rudders** [comment]
That's kind of peculiar - can you tell me what OS you are on please? and maybe version of node? I con;t figure out why it's not evaluating correctly.

**Comment by rudders** [comment]
fixed in V0.6.6

**Comment by rudders** [comment]
Re-opened for Grouped Bulbs

**Comment by jmelby70** [comment]
Sorry, I didn't get you my os info in the last reply--I'm on Mac OS 10.11.2, using Node version 5.5.0. Unfortunately, the update you made (0.6.6) didn't actually resolve the homekit_safe issue for me. It still crashes after the timeout, even trying the multiple variations of quotes and 0 vs. false.

**Comment by jmelby70** [comment]
Also, just to note that this setting worked fine in 0.6.4. It was only when upgrading to 0.6.5 that it stopped working.

**Comment by rudders** [comment]
Please try removing the quote marks from the expected_accessories parameter. #mybad

**Comment by jmelby70** [comment]
That doesn't seem to make a difference... current config is:

    "platforms": [
        {
          "platform": "BelkinWeMo",
          "name": "WeMo Platform",
          "expected_accessories": 12,
          "timeout" : "120",
          "no_motion_timer": "60",
          "homekit_safe": 0
        }
    ]

**Comment by rudders** [comment]
Although I'd discover disabling HomeKit Safe. I'd find an expected_accessories parameter that worked if possible.
Can you use HomeKit zones/rooms instead of WEMO Groups?

**Comment by rudders** [comment]
But I though it only ever found 11 devices. I haven't fixed the group issue.

**Comment by jmelby70** [comment]
It works fine when I use "expected_accessories": 11, which is what actually gets discovered without the second light group. I prefer to use Wemo groups because I'd still like to use the Wemo app to control the group when doing it with my hands--I was mainly wanting to use HomeKit for voice control. The problem is that the MyTouchHome app is a bit clunkier to use. Also, not sure how that works if you have multiple devices--do you have to set up the zones/rooms on each one?

**Comment by rudders** [comment]
you can quite arbitrarily set up zones and rooms - Insteon+ (use and good), EVE (don;t use but have had good reports) and Home ($$$) are probably better choices than MyTouchHome in my humble opinion.

**Comment by rudders** [comment]
I've had a bit of a look and groups of bulbs should work fine! 
Can you run `DEBUG=wemo-client home bridge` with the expected_accessories = 12 (which will error) and send me the complete log you get please. I'd like to see if it's discovered and I ignore it or if it's simply not discovered. Is it the same group each time that's not found?

**Comment by rudders** [comment]
Can you confirm that the expected_accessories / homekit_safe parameters are working correctly and that the only issue is the grouped bulbs please.

**Comment by jmelby70** [comment]
The homekit_safe parameter still doesn't work when set to 0... if I have expected_accessories = 12, it will still intentionally crash. If I set expected_accessories = 11, it starts up fine because it discovers 11. So, it's treating it as though homekit_safe = 1. This is on version 0.6.6, which I updated to when you said it was fixed.

I've attached the output from running homebridge with debug on. The light group that is never found is named "Downstairs Hall Lights", which I don't see in the output at all, so it appears to never discover it. It is always the same light group that is never found. The other light group is "Living Room Lights". I've also attached a screenshot of the Wemo app showing the 2 light groups.

[homebridgeout.txt](https://github.com/rudders/homebridge-platform-wemo/files/110257/homebridgeout.txt)
![img_0332](https://cloud.githubusercontent.com/assets/11700569/12685294/23729eee-c689-11e5-916d-5c74755fcebb.jpg)

**Comment by rudders** [comment]
Are the groups of lights on the same bridge or are there two bridges?

Sorry to stuff you around but could you 
`sudo npm install -g https://github.com/rudders/homebridge-platform-wemo.git#group-test` and run homebridge again without DEBUG is find and again send me you logs.

**Comment by jmelby70** [comment]
Well I don't know what "stuff you around" means (must be an Aussie expression?), but it's no problem!

I only have one Wemo Link bridge, so both groups are from the same one. I've attached the output from running with the group-test version.

[homebridgeout2.txt](https://github.com/rudders/homebridge-platform-wemo/files/110323/homebridgeout2.txt)

**Comment by rudders** [comment]
Yes it is an Aussie thing - I was apologising for making you do all this work because of what is probably my bad coding.

So - the wemo-client module I depend on is not telling us about the other group - so I'll go digging there.

In the mean time can you redo the install step above and post one more log.

**Comment by jmelby70** [comment]
sure... here's the output from the latest

[homebridgeout3.txt](https://github.com/rudders/homebridge-platform-wemo/files/110348/homebridgeout3.txt)

**Comment by jmelby70** [comment]
Another... I realized I had left homekit_safe as 1... I tried that thinking maybe the flag was flipped. Here it is with 0.

[homebridgeout4.txt](https://github.com/rudders/homebridge-platform-wemo/files/110355/homebridgeout4.txt)

**Comment by rudders** [comment]
Thanks again.


1. I notice that `homekit_safe` is set to 1 in your config ?
2. And we're still not seeing all the bulb groups so I've added some debug to wemo-client.

So i'd like you to reinstall and run with DEBUG=wemo-client again please.

Adrian

**Comment by jmelby70** [comment]
Here's the latest with debug on
[homebridgeout5.txt](https://github.com/rudders/homebridge-platform-wemo/files/110371/homebridgeout5.txt)

**Comment by rudders** [comment]
Thanks - I'm on it....

**Comment by IMNotMax** [comment]
Hi,
I had a similar issue, try to rename with a short name your group.
One of my switch was not discovered, and changing "interrupteur télé et
lumière" to "wemo3" make it works. (Maybe the French accents were the
cause, it's an idea :)


Le vendredi 29 janvier 2016, Adrian Rudman <notifications@github.com> a
écrit :

**Comment by jmelby70** [comment]
Thanks for the suggestion, IMNotMax, but I tried renaming the group to just "Hall" and it still didn't find the group. It looks like the latest debug log shows that wemo-client module actually finds the group, so I suspect its a bug that only exposes one group to the platform code.

**Comment by rudders** [comment]
Ill look into WEMO-client as it does appear to be in there. Shouldn't be to hard when I get a few minutes to concentrate.

**Comment by rudders** [comment]
@jmelby70 - when will you be available to test? I can't test it very well with my current setup and will make you a special release.

**Comment by jmelby70** [comment]
I'm around most of the weekend here, so whenever you have a test build ready I can try it out.

**Comment by rudders** [comment]
It's ready to go, just reinstall and run as per the previous instructions.

**Comment by jmelby70** [comment]
Woo hoo! Looks like its working now...

[WeMo Platform] 2 EndDevices found in: [ { friendlyName: 'Living Room Lights',
    deviceId: '1439858321',
    capabilities: 
     { '10006': '1',
       '10008': '255:0',
       '30008': '0:0',
       '30009': '',
       '3000A': '' },
    deviceType: 'dimmableLight' },
  { friendlyName: 'Downstairs Hall Lights',
    deviceId: '1453771038',
    capabilities: 
     { '10006': '1',
       '10008': '51:0',
       '30008': '0:0',
       '30009': '',
       '3000A': '' },
    deviceType: 'dimmableLight' } ]
[WeMo Platform] Found endDevice: Living Room Lights, id: 1439858321
[WeMo Platform] Discovered 11 accessories of 12 
[WeMo Platform] Found endDevice: Downstairs Hall Lights, id: 1453771038
[WeMo Platform] Discovered 12 accessories of 12 

Thanks again for all of your help!

**Comment by rudders** [comment]
Sweet! Excellent news! I'll fold it back into a release and let you now what to update to. The major issue is in a sub-module so will have to wait for a pull request processed so stay on the version you have till I close this Issue - thanks for your patience.

**Comment by craigdent** [comment]
I'm having similar issue as it's crashing when it's discovering 1 group

Says

**Comment by rudders** [comment]
Can you provide a complete log from when homebridge starts please and confirm versions of Homebridge and the plugin please.

**Comment by craigdent** [comment]
Bulb reportered as at 100% brightness
Events.js:141
  Throw er; // unhandled 'error' event
  ^

TypeError: cannot read property 'length' of undefined

**Comment by craigdent** [comment]
How do I get the version of each of them

**Comment by rudders** [comment]
Can you provide the log from starting homebridge to the error please and all of the error message - the lines following what you provide give detail of which code is falling over.

```sudo npm -g ls homebridge```
```sudo npm -g ls homebridge-platform-wemo```

**Comment by craigdent** [comment]
Homebridge@0.2.17
Homebridge-platform-wemo@0.6.9

Regards,
Craig Dent

**Comment by rudders** [comment]
I really need to see all of the log to help you resolve the issue. I don't even know what module has crashed.
And some idea of your wemo setup will also help - how many Groups to you have for instance? How many other devices?

**Comment by craigdent** [comment]
How do I get the log?
I have 2 Wemo motion, 1 insight and 3 bulbs
2 bulbs are grouped and 1 is by itself

Used to work but since stopped since updating

**Comment by rudders** [comment]
When you start homebridge it starts outputting lots of information to the console or to the log file depending on how you've installed if.

If you can run homebridge from the command line just try `homebridge -D` - copy and paste the output into the issue will do.

The fact that you updated is a interesting bit of information - what did you upgrade?

**Comment by craigdent** [comment]
Ok I'll get the log shortly
I updated the homebridge and platform-Wemo-client using npm update command

I regularly run this as well as apt-get update & upgrade

None of the other devices seem to error like the Wemo

**Comment by rudders** [comment]
Try `npm install` rather than update.
Have you upgraded node recently also? 5.6 has some issues for some plugins `node -v` to find out mode version.
And what operating system too when you get a chance.
I'm travelling on business so may not be this responsive later in the day.

**Comment by craigdent** [comment]
Ok I'll try the npm install

Also running node v4.0.0

**Comment by rudders** [comment]
Any update on this issue?

**Comment by rudders** [comment]
@craigdent did you resolve your issue?

**Comment by craigdent** [comment]
Nope still happening. It picks up the devices but still errors out on 'length'

Regards,
Craig Dent

**Comment by rudders** [comment]
Can you provide a log from starting homebridge to the error occurring please.

**Comment by craigdent** [comment]
pi@raspberrypi ~ $ homebridge

*** WARNING *** The program 'node' uses the Apple Bonjour compatibility layer of                             Avahi.

*** WARNING *** Please fix your application to use the native API of Avahi!

*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libd                            ns_sd&e=node>

*** WARNING *** The program 'node' called 'DNSServiceRegister()' which is not su                            pported (or only supported partially) in the Apple Bonjour compatibility layer o                            f Avahi.

*** WARNING *** Please fix your application to use the native API of Avahi!

*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libd                            ns_sd&e=node&f=DNSServiceRegister>

Loaded plugin: homebridge-applescript

Registering accessory 'homebridge-applescript.Applescript'

---

*** WARNING *** The program 'node' called 'DNSServiceRegister()' which is not su                            pported (or only supported partially) in the Apple Bonjour compatibility layer o                            f Avahi.

*** WARNING *** Please fix your application to use the native API of Avahi!

*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libd                            ns_sd&e=node&f=DNSServiceRegister>

Loaded plugin: homebridge-controllerlink

Registering platform 'homebridge-controllerlink.HomeBridgeControllerLink'

---

Loaded plugin: homebridge-foscam

Registering accessory 'homebridge-foscam.Foscam'

---

Loaded plugin: homebridge-harmonyhub

Registering platform 'homebridge-harmonyhub.HarmonyHub'

---

Loaded plugin: homebridge-ifttt

Registering platform 'homebridge-ifttt.IFTTT'

---

Loaded plugin: homebridge-kevo

Registering accessory 'homebridge-kevo.Kevo'

---

Loaded plugin: homebridge-legacy-plugins

Registering accessory 'homebridge-legacy-plugins.AD2USB'

Registering accessory 'homebridge-legacy-plugins.Carwings'

Registering accessory 'homebridge-legacy-plugins.ELKM1'

Registering accessory 'homebridge-legacy-plugins.FileSensor'

Registering accessory 'homebridge-legacy-plugins.GenericRS232Device'

Registering accessory 'homebridge-legacy-plugins.HomeMatic'

Registering accessory 'homebridge-legacy-plugins.HomeMaticThermo'

Registering accessory 'homebridge-legacy-plugins.HomeMaticWindow'

Registering accessory 'homebridge-legacy-plugins.HttpGarageDoorOpener'

Registering accessory 'homebridge-legacy-plugins.HttpHygrometer'

Registering accessory 'homebridge-legacy-plugins.HttpThermometer'

Registering accessory 'homebridge-legacy-plugins.Tesla'

Registering accessory 'homebridge-legacy-plugins.X10'

Registering accessory 'homebridge-legacy-plugins.mpdclient'

Registering platform 'homebridge-legacy-plugins.Domoticz'

Registering platform 'homebridge-legacy-plugins.HomeAssistant'

Registering platform 'homebridge-legacy-plugins.HomeSeer'

Registering platform 'homebridge-legacy-plugins.ISY'

Registering platform 'homebridge-legacy-plugins.LIFx'

Registering platform 'homebridge-legacy-plugins.SmartThings'

Registering platform 'homebridge-legacy-plugins.TelldusLive'

Registering platform 'homebridge-legacy-plugins.ZWayServer'

---

Loaded plugin: homebridge-lifx

Registering accessory 'homebridge-lifx-bulb.LIFxBulb'

Registering platform 'homebridge-lifx.LIFx'

---

Loaded plugin: homebridge-lifx-lan

Registering platform 'homebridge-lifx-lan.LifxLan'

---

Loaded plugin: homebridge-milight

Registering platform 'homebridge-milight.MiLight'

---

Loaded plugin: homebridge-netatmo

Registering platform 'homebridge-netatmo.netatmo'

---

Loaded plugin: homebridge-people

Registering accessory 'homebridge-people.people'

---

Loaded plugin: homebridge-philipshue

Registering platform 'homebridge-philipshue.PhilipsHue'

---

Loaded plugin: homebridge-platform-wemo

Registering platform 'homebridge-platform-wemo.BelkinWeMo'

---

Loaded plugin: homebridge-samsungtv

Registering accessory 'homebridge-samsungtv.SamsungTV'

---

Loaded plugin: homebridge-wunderground

Registering accessory 'homebridge-wunderground.WUNDERGROUND'

---

Loaded config.json with 3 accessories and 6 platforms.

---

Loading 6 platforms...

[MiLight] Initializing MiLight platform...

[MiLight] Initializing platform accessory 'Front'...

[MiLight] Initializing platform accessory 'Back'...

Initializing HomeBridgeControllerLink platform...

[WeMo Platform] Initializing BelkinWeMo platform...

[WeMo Platform] Wemo Platform Plugin Loaded

[WeMo Platform] Fetching the Wemo Accessories, expecting an unknown number and will wait 60 seconds to find them.

[netatmo weather] Initializing netatmo platform...

[LiFx] Initializing LifxLan platform...

[Living Room Harmony Hub] Initializing HarmonyHub platform...

[Living Room Harmony Hub] Searching for Logitech Harmony remote hubs...

Loading 3 accessories...

[TV Living room] Initializing SamsungTV accessory...

[Foscam_Garage] Initializing Foscam accessory...

[People] Initializing people accessory...

[LiFx] Server Listening...

[WeMo Platform] Found: WeMo Insight, type: insight

[WeMo Platform] WeMo Insight is true

[WeMo Platform] Discovered 1 accessories of an unspecified number of accessories

[WeMo Platform] Found: WeMo Motion - Passage Way, type: sensor

[WeMo Platform] WeMo Motion - Passage Way is false

[WeMo Platform] Discovered 2 accessories of an unspecified number of accessories

[WeMo Platform] Found: WeMo Motion - Master Bedroom, type: sensor

[WeMo Platform] WeMo Motion - Master Bedroom is false

[WeMo Platform] Discovered 3 accessories of an unspecified number of accessories

[WeMo Platform] Found: WeMo Link, type: bridge

[LiFx] Online: Living [d073d5016fa9]

[LiFx] Online: Craig Lamp [d073d50337ea]

/usr/local/lib/node_modules/homebridge-platform-wemo/index.js:72

                    self.log("%s EndDevices found in:", enddevices.length );

                                                                  ^

 

TypeError: Cannot read property 'length' of undefined

    at /usr/local/lib/node_modules/homebridge-platform-wemo/index.js:72:67

    at parseResponse (/usr/local/lib/node_modules/homebridge-platform-wemo/node_modules/wemo-client/client.js:144:21)

    at /usr/local/lib/node_modules/homebridge-platform-wemo/node_modules/wemo-client/client.js:104:21

    at ClientRequest.<anonymous> (/usr/local/lib/node_modules/homebridge-platform-wemo/node_modules/wemo-client/client.js:77:5)

    at emitOne (events.js:77:13)

    at ClientRequest.emit (events.js:169:7)

    at Socket.socketCloseListener (_http_client.js:235:9)

    at emitOne (events.js:82:20)

    at Socket.emit (events.js:169:7)

    at TCP._onclose (net.js:469:12)

**Comment by rudders** [comment]
Well that's far more interesting - how many bulbs are associated with that bridge (Wemo Link)?

It would be good to get some debug output.

`DEBUG=wemo-client homebridge`.

and provide all of that log/output please.

**Comment by craigdent** [comment]
I have 3 bulbs

2 are grouped (the master bedroom ones)

 

 

pi@raspberrypi ~ $ DEBUG=wemo-client homebridge

*** WARNING *** The program 'node' uses the Apple Bonjour compatibility layer of                                                                                                                                                              Avahi.

*** WARNING *** Please fix your application to use the native API of Avahi!

*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libd                                                                                                                                                             ns_sd&e=node>

*** WARNING *** The program 'node' called 'DNSServiceRegister()' which is not su                                                                                                                                                             pported (or only supported partially) in the Apple Bonjour compatibility layer o                                                                                                                                                             f Avahi.

*** WARNING *** Please fix your application to use the native API of Avahi!

*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libd                                                                                                                                                             ns_sd&e=node&f=DNSServiceRegister>

Loaded plugin: homebridge-applescript

Registering accessory 'homebridge-applescript.Applescript'

---

*** WARNING *** The program 'node' called 'DNSServiceRegister()' which is not su                                                                                                                                                             pported (or only supported partially) in the Apple Bonjour compatibility layer o                                                                                                                                                             f Avahi.

*** WARNING *** Please fix your application to use the native API of Avahi!

*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libd                                                                                                                                                             ns_sd&e=node&f=DNSServiceRegister>

Loaded plugin: homebridge-controllerlink

Registering platform 'homebridge-controllerlink.HomeBridgeControllerLink'

---

Loaded plugin: homebridge-foscam

Registering accessory 'homebridge-foscam.Foscam'

---

Loaded plugin: homebridge-harmonyhub

Registering platform 'homebridge-harmonyhub.HarmonyHub'

---

Loaded plugin: homebridge-ifttt

Registering platform 'homebridge-ifttt.IFTTT'

---

Loaded plugin: homebridge-kevo

Registering accessory 'homebridge-kevo.Kevo'

---

Loaded plugin: homebridge-legacy-plugins

Registering accessory 'homebridge-legacy-plugins.AD2USB'

Registering accessory 'homebridge-legacy-plugins.Carwings'

Registering accessory 'homebridge-legacy-plugins.ELKM1'

Registering accessory 'homebridge-legacy-plugins.FileSensor'

Registering accessory 'homebridge-legacy-plugins.GenericRS232Device'

Registering accessory 'homebridge-legacy-plugins.HomeMatic'

Registering accessory 'homebridge-legacy-plugins.HomeMaticThermo'

Registering accessory 'homebridge-legacy-plugins.HomeMaticWindow'

Registering accessory 'homebridge-legacy-plugins.HttpGarageDoorOpener'

Registering accessory 'homebridge-legacy-plugins.HttpHygrometer'

Registering accessory 'homebridge-legacy-plugins.HttpThermometer'

Registering accessory 'homebridge-legacy-plugins.Tesla'

Registering accessory 'homebridge-legacy-plugins.X10'

Registering accessory 'homebridge-legacy-plugins.mpdclient'

Registering platform 'homebridge-legacy-plugins.Domoticz'

Registering platform 'homebridge-legacy-plugins.HomeAssistant'

Registering platform 'homebridge-legacy-plugins.HomeSeer'

Registering platform 'homebridge-legacy-plugins.ISY'

Registering platform 'homebridge-legacy-plugins.LIFx'

Registering platform 'homebridge-legacy-plugins.SmartThings'

Registering platform 'homebridge-legacy-plugins.TelldusLive'

Registering platform 'homebridge-legacy-plugins.ZWayServer'

---

Loaded plugin: homebridge-lifx

Registering accessory 'homebridge-lifx-bulb.LIFxBulb'

Registering platform 'homebridge-lifx.LIFx'

---

Loaded plugin: homebridge-lifx-lan

Registering platform 'homebridge-lifx-lan.LifxLan'

---

Loaded plugin: homebridge-milight

Registering platform 'homebridge-milight.MiLight'

---

Loaded plugin: homebridge-netatmo

Registering platform 'homebridge-netatmo.netatmo'

---

Loaded plugin: homebridge-people

Registering accessory 'homebridge-people.people'

---

Loaded plugin: homebridge-philipshue

Registering platform 'homebridge-philipshue.PhilipsHue'

---

Loaded plugin: homebridge-platform-wemo

Registering platform 'homebridge-platform-wemo.BelkinWeMo'

---

Loaded plugin: homebridge-samsungtv

Registering accessory 'homebridge-samsungtv.SamsungTV'

---

Loaded plugin: homebridge-wunderground

Registering accessory 'homebridge-wunderground.WUNDERGROUND'

---

Loaded config.json with 3 accessories and 6 platforms.

---

Loading 6 platforms...

[MiLight] Initializing MiLight platform...

[MiLight] Initializing platform accessory 'Front'...

[MiLight] Initializing platform accessory 'Back'...

Initializing HomeBridgeControllerLink platform...

[WeMo Platform] Initializing BelkinWeMo platform...

[WeMo Platform] Wemo Platform Plugin Loaded

[WeMo Platform] Fetching the Wemo Accessories, expecting an unknown number and w                                                                                                                                                             ill wait 60 seconds to find them.

[netatmo weather] Initializing netatmo platform...

[LiFx] Initializing LifxLan platform...

[Living Room Harmony Hub] Initializing HarmonyHub platform...

[Living Room Harmony Hub] Searching for Logitech Harmony remote hubs...

Loading 3 accessories...

[TV Living room] Initializing SamsungTV accessory...

[Foscam_Garage] Initializing Foscam accessory...

[People] Initializing people accessory...

[LiFx] Server Listening...

  wemo-client Found device: {"root":{"$":{"xmlns":"urn:Belkin:device-1-0"},"spec                                                                                                                                                             Version":{"major":"1","minor":"0"},"device":{"deviceType":"urn:Belkin:device:sen                                                                                                                                                             sor:1","friendlyName":"WeMo Motion - Passage Way","manufacturer":"Belkin Interna                                                                                                                                                             tional Inc.","manufacturerURL":"http://www.belkin.com","modelDescription":"Belki                                                                                                                                                             n Plugin Socket 1.0","modelName":"Sensor","modelNumber":"1.0","modelURL":"http:/                                                                                                                                                             /www.belkin.com/plugin/","serialNumber":"221306L110015B","UDN":"uuid:Sensor-1_0-                                                                                                                                                             221306L110015B","UPC":"123456789","macAddress":"EC1A597948B0","firmwareVersion":                                                                                                                                                             "WeMo_WW_2.00.10062.PVT-OWRT-SNS","iconVersion":"0|49153","binaryState":"0","ico                                                                                                                                                             nList":{"icon":{"mimetype":"jpg","width":"100","height":"100","depth":"100","url                                                                                                                                                             ":"icon.jpg"}},"serviceList":{"service":[{"serviceType":"urn:Belkin:service:WiFi                                                                                                                                                             Setup:1","serviceId":"urn:Belkin:serviceId:WiFiSetup1","controlURL":"/upnp/contr                                                                                                                                                             ol/WiFiSetup1","eventSubURL":"/upnp/event/WiFiSetup1","SCPDURL":"/setupservice.x                                                                                                                                                             ml"},{"serviceType":"urn:Belkin:service:timesync:1","serviceId":"urn:Belkin:serv                                                                                                                                                             iceId:timesync1","controlURL":"/upnp/control/timesync1","eventSubURL":"/upnp/eve                                                                                                                                                             nt/timesync1","SCPDURL":"/timesyncservice.xml"},{"serviceType":"urn:Belkin:servi                                                                                                                                                             ce:basicevent:1","serviceId":"urn:Belkin:serviceId:basicevent1","controlURL":"/u                                                                                                                                                             pnp/control/basicevent1","eventSubURL":"/upnp/event/basicevent1","SCPDURL":"/eve                                                                                                                                                             ntservice.xml"},{"serviceType":"urn:Belkin:service:firmwareupdate:1","serviceId"                                                                                                                                                             :"urn:Belkin:serviceId:firmwareupdate1","controlURL":"/upnp/control/firmwareupda                                                                                                                                                             te1","eventSubURL":"/upnp/event/firmwareupdate1","SCPDURL":"/firmwareupdate.xml"                                                                                                                                                             },{"serviceType":"urn:Belkin:service:rules:1","serviceId":"urn:Belkin:serviceId:                                                                                                                                                             rules1","controlURL":"/upnp/control/rules1","eventSubURL":"/upnp/event/rules1","                                                                                                                                                             SCPDURL":"/rulesservice.xml"},{"serviceType":"urn:Belkin:service:metainfo:1","se                                                                                                                                                             rviceId":"urn:Belkin:serviceId:metainfo1","controlURL":"/upnp/control/metainfo1"                                                                                                                                                             ,"eventSubURL":"/upnp/event/metainfo1","SCPDURL":"/metainfoservice.xml"},{"servi                                                                                                                                                             ceType":"urn:Belkin:service:remoteaccess:1","serviceId":"urn:Belkin:serviceId:re                                                                                                                                                             moteaccess1","controlURL":"/upnp/control/remoteaccess1","eventSubURL":"/upnp/eve                                                                                                                                                             nt/remoteaccess1","SCPDURL":"/remoteaccess.xml"},{"serviceType":"urn:Belkin:serv                                                                                                                                                             ice:deviceinfo:1","serviceId":"urn:Belkin:serviceId:deviceinfo1","controlURL":"/                                                                                                                                                             upnp/control/deviceinfo1","eventSubURL":"/upnp/event/deviceinfo1","SCPDURL":"/de                                                                                                                                                             viceinfoservice.xml"},{"serviceType":"urn:Belkin:service:smartsetup:1","serviceI                                                                                                                                                             d":"urn:Belkin:serviceId:smartsetup1","controlURL":"/upnp/control/smartsetup1","                                                                                                                                                             eventSubURL":"/upnp/event/smartsetup1","SCPDURL":"/smartsetup.xml"},{"serviceTyp                                                                                                                                                             e":"urn:Belkin:service:manufacture:1","serviceId":"urn:Belkin:serviceId:manufact                                                                                                                                                             ure1","controlURL":"/upnp/control/manufacture1","eventSubURL":"/upnp/event/manuf                                                                                                                                                             acture1","SCPDURL":"/manufacture.xml"}]},"presentationURL":"/pluginpres.html","h                                                                                                                                                             ost":"10.26.100.64","port":"49153","callbackURL":"http://10.26.100.96:36448"}}}                                                                                                                                                              +0ms

[WeMo Platform] Found: WeMo Motion - Passage Way, type: sensor

[WeMo Platform] WeMo Motion - Passage Way is false

  wemo-client Initial subscription - Device: uuid:Sensor-1_0-221306L110015B, Ser                                                                                                                                                             vice: urn:Belkin:service:basicevent:1 +26ms

[WeMo Platform] Discovered 1 accessories of an unspecified number of accessories                                                                                                                                                             

  wemo-client Found device: {"root":{"$":{"xmlns":"urn:Belkin:device-1-0"},"spec                                                                                                                                                             Version":{"major":"1","minor":"0"},"device":{"deviceType":"urn:Belkin:device:bri                                                                                                                                                             dge:1","friendlyName":"WeMo Link","manufacturer":"Belkin International Inc.","ma                                                                                                                                                             nufacturerURL":"http://www.belkin.com","modelDescription":"Belkin WeMo Wi-Fi to                                                                                                                                                              ZigBee Bridge","modelName":"Bridge","modelNumber":"1.0","modelURL":"http://www.b                                                                                                                                                             elkin.com/plugin/","serialNumber":"231445B01013D0","UDN":"uuid:Bridge-1_0-231445                                                                                                                                                             B01013D0","UPC":"123456789","macAddress":"94103ECCEF7C","firmwareVersion":"WeMo_                                                                                                                                                             WW_2.00.10114.PVT-OWRT-Link","iconVersion":"0|49153","binaryState":"0","iconList                                                                                                                                                             ":{"icon":{"mimetype":"jpg","width":"100","height":"100","depth":"100","url":"ic                                                                                                                                                             on.jpg"}},"serviceList":{"service":[{"serviceType":"urn:Belkin:service:WiFiSetup                                                                                                                                                             :1","serviceId":"urn:Belkin:serviceId:WiFiSetup1","controlURL":"/upnp/control/Wi                                                                                                                                                             FiSetup1","eventSubURL":"/upnp/event/WiFiSetup1","SCPDURL":"/setupservice.xml"},                                                                                                                                                             {"serviceType":"urn:Belkin:service:timesync:1","serviceId":"urn:Belkin:serviceId                                                                                                                                                             :timesync1","controlURL":"/upnp/control/timesync1","eventSubURL":"/upnp/event/ti                                                                                                                                                             mesync1","SCPDURL":"/timesyncservice.xml"},{"serviceType":"urn:Belkin:service:ba                                                                                                                                                             sicevent:1","serviceId":"urn:Belkin:serviceId:basicevent1","controlURL":"/upnp/c                                                                                                                                                             ontrol/basicevent1","eventSubURL":"/upnp/event/basicevent1","SCPDURL":"/eventser                                                                                                                                                             vice.xml"},{"serviceType":"urn:Belkin:service:firmwareupdate:1","serviceId":"urn                                                                                                                                                             :Belkin:serviceId:firmwareupdate1","controlURL":"/upnp/control/firmwareupdate1",                                                                                                                                                             "eventSubURL":"/upnp/event/firmwareupdate1","SCPDURL":"/firmwareupdate.xml"},{"s                                                                                                                                                             erviceType":"urn:Belkin:service:rules:1","serviceId":"urn:Belkin:serviceId:rules                                                                                                                                                             1","controlURL":"/upnp/control/rules1","eventSubURL":"/upnp/event/rules1","SCPDU                                                                                                                                                             RL":"/bridgerules.xml"},{"serviceType":"urn:Belkin:service:metainfo:1","serviceI                                                                                                                                                             d":"urn:Belkin:serviceId:metainfo1","controlURL":"/upnp/control/metainfo1","even                                                                                                                                                             tSubURL":"/upnp/event/metainfo1","SCPDURL":"/metainfoservice.xml"},{"serviceType                                                                                                                                                             ":"urn:Belkin:service:remoteaccess:1","serviceId":"urn:Belkin:serviceId:remoteac                                                                                                                                                             cess1","controlURL":"/upnp/control/remoteaccess1","eventSubURL":"/upnp/event/rem                                                                                                                                                             oteaccess1","SCPDURL":"/remoteaccess.xml"},{"serviceType":"urn:Belkin:service:de                                                                                                                                                             viceinfo:1","serviceId":"urn:Belkin:serviceId:deviceinfo1","controlURL":"/upnp/c                                                                                                                                                             ontrol/deviceinfo1","eventSubURL":"/upnp/event/deviceinfo1","SCPDURL":"/devicein                                                                                                                                                             foservice.xml"},{"serviceType":"urn:Belkin:service:bridge:1","serviceId":"urn:Be                                                                                                                                                             lkin:serviceId:bridge1","controlURL":"/upnp/control/bridge1","eventSubURL":"/upn                                                                                                                                                             p/event/bridge1","SCPDURL":"/bridgeservice.xml"},{"serviceType":"urn:Belkin:serv                                                                                                                                                             ice:manufacture:1","serviceId":"urn:Belkin:serviceId:manufacture1","controlURL":                                                                                                                                                             "/upnp/control/manufacture1","eventSubURL":"/upnp/event/manufacture1","SCPDURL":                                                                                                                                                             "/manufacture.xml"}]},"presentationURL":"/pluginpres.html","host":"10.26.100.89"                                                                                                                                                             ,"port":"49153","callbackURL":"http://10.26.100.96:36448"}}} +133ms

[WeMo Platform] Found: WeMo Link, type: bridge

  wemo-client Found device: {"root":{"$":{"xmlns":"urn:Belkin:device-1-0"},"spec                                                                                                                                                             Version":{"major":"1","minor":"0"},"device":{"deviceType":"urn:Belkin:device:ins                                                                                                                                                             ight:1","friendlyName":"WeMo Insight","manufacturer":"Belkin International Inc."                                                                                                                                                             ,"manufacturerURL":"http://www.belkin.com","modelDescription":"Belkin Insight 1.                                                                                                                                                             0","modelName":"Insight","modelNumber":"1.0","modelURL":"http://www.belkin.com/p                                                                                                                                                             lugin/","serialNumber":"221520K12007EB","UDN":"uuid:Insight-1_0-221520K12007EB",                                                                                                                                                             "UPC":"123456789","macAddress":"94103E4BCC48","firmwareVersion":"WeMo_WW_2.00.10                                                                                                                                                             062.PVT-OWRT-Insight","iconVersion":"0|49153","binaryState":"1","iconList":{"ico                                                                                                                                                             n":{"mimetype":"jpg","width":"100","height":"100","depth":"100","url":"icon.jpg"                                                                                                                                                             }},"serviceList":{"service":[{"serviceType":"urn:Belkin:service:WiFiSetup:1","se                                                                                                                                                             rviceId":"urn:Belkin:serviceId:WiFiSetup1","controlURL":"/upnp/control/WiFiSetup                                                                                                                                                             1","eventSubURL":"/upnp/event/WiFiSetup1","SCPDURL":"/setupservice.xml"},{"servi                                                                                                                                                             ceType":"urn:Belkin:service:timesync:1","serviceId":"urn:Belkin:serviceId:timesy                                                                                                                                                             nc1","controlURL":"/upnp/control/timesync1","eventSubURL":"/upnp/event/timesync1                                                                                                                                                             ","SCPDURL":"/timesyncservice.xml"},{"serviceType":"urn:Belkin:service:basiceven                                                                                                                                                             t:1","serviceId":"urn:Belkin:serviceId:basicevent1","controlURL":"/upnp/control/                                                                                                                                                             basicevent1","eventSubURL":"/upnp/event/basicevent1","SCPDURL":"/eventservice.xm                                                                                                                                                             l"},{"serviceType":"urn:Belkin:service:firmwareupdate:1","serviceId":"urn:Belkin                                                                                                                                                             :serviceId:firmwareupdate1","controlURL":"/upnp/control/firmwareupdate1","eventS                                                                                                                                                             ubURL":"/upnp/event/firmwareupdate1","SCPDURL":"/firmwareupdate.xml"},{"serviceT                                                                                                                                                             ype":"urn:Belkin:service:rules:1","serviceId":"urn:Belkin:serviceId:rules1","con                                                                                                                                                             trolURL":"/upnp/control/rules1","eventSubURL":"/upnp/event/rules1","SCPDURL":"/r                                                                                                                                                             ulesservice.xml"},{"serviceType":"urn:Belkin:service:metainfo:1","serviceId":"ur                                                                                                                                                             n:Belkin:serviceId:metainfo1","controlURL":"/upnp/control/metainfo1","eventSubUR                                                                                                                                                             L":"/upnp/event/metainfo1","SCPDURL":"/metainfoservice.xml"},{"serviceType":"urn                                                                                                                                                             :Belkin:service:remoteaccess:1","serviceId":"urn:Belkin:serviceId:remoteaccess1"                                                                                                                                                             ,"controlURL":"/upnp/control/remoteaccess1","eventSubURL":"/upnp/event/remoteacc                                                                                                                                                             ess1","SCPDURL":"/remoteaccess.xml"},{"serviceType":"urn:Belkin:service:devicein                                                                                                                                                             fo:1","serviceId":"urn:Belkin:serviceId:deviceinfo1","controlURL":"/upnp/control                                                                                                                                                             /deviceinfo1","eventSubURL":"/upnp/event/deviceinfo1","SCPDURL":"/deviceinfoserv                                                                                                                                                             ice.xml"},{"serviceType":"urn:Belkin:service:insight:1","serviceId":"urn:Belkin:                                                                                                                                                             serviceId:insight1","controlURL":"/upnp/control/insight1","eventSubURL":"/upnp/e                                                                                                                                                             vent/insight1","SCPDURL":"/insightservice.xml"},{"serviceType":"urn:Belkin:servi                                                                                                                                                             ce:smartsetup:1","serviceId":"urn:Belkin:serviceId:smartsetup1","controlURL":"/u                                                                                                                                                             pnp/control/smartsetup1","eventSubURL":"/upnp/event/smartsetup1","SCPDURL":"/sma                                                                                                                                                             rtsetup.xml"},{"serviceType":"urn:Belkin:service:manufacture:1","serviceId":"urn                                                                                                                                                             :Belkin:serviceId:manufacture1","controlURL":"/upnp/control/manufacture1","event                                                                                                                                                             SubURL":"/upnp/event/manufacture1","SCPDURL":"/manufacture.xml"}]},"presentation                                                                                                                                                             URL":"/pluginpres.html","host":"10.26.100.68","port":"49153","callbackURL":"http                                                                                                                                                             ://10.26.100.96:36448"}}} +109ms

[WeMo Platform] Found: WeMo Insight, type: insight

[WeMo Platform] WeMo Insight is true

  wemo-client Initial subscription - Device: uuid:Insight-1_0-221520K12007EB, Se                                                                                                                                                             rvice: urn:Belkin:service:basicevent:1 +9ms

  wemo-client Initial subscription - Device: uuid:Insight-1_0-221520K12007EB, Se                                                                                                                                                             rvice: urn:Belkin:service:insight:1 +6ms

[WeMo Platform] Discovered 2 accessories of an unspecified number of accessories                                                                                                                                                             

[LiFx] Online: Living [d073d5016fa9]

  wemo-client Found device: {"root":{"$":{"xmlns":"urn:Belkin:device-1-0"},"spec                                                                                                                                                             Version":{"major":"1","minor":"0"},"device":{"deviceType":"urn:Belkin:device:sen                                                                                                                                                             sor:1","friendlyName":"WeMo Motion - Master Bedroom","manufacturer":"Belkin Inte                                                                                                                                                             rnational Inc.","manufacturerURL":"http://www.belkin.com","modelDescription":"Be                                                                                                                                                             lkin Plugin Socket 1.0","modelName":"Sensor","modelNumber":"1.0","modelURL":"htt                                                                                                                                                             p://www.belkin.com/plugin/","serialNumber":"221312L1101343","UDN":"uuid:Sensor-1                                                                                                                                                             _0-221312L1101343","UPC":"123456789","macAddress":"EC1A597B990C","firmwareVersio                                                                                                                                                             n":"WeMo_WW_2.00.10062.PVT-OWRT-SNS","iconVersion":"0|49154","binaryState":"0","                                                                                                                                                             iconList":{"icon":{"mimetype":"jpg","width":"100","height":"100","depth":"100","                                                                                                                                                             url":"icon.jpg"}},"serviceList":{"service":[{"serviceType":"urn:Belkin:service:W                                                                                                                                                             iFiSetup:1","serviceId":"urn:Belkin:serviceId:WiFiSetup1","controlURL":"/upnp/co                                                                                                                                                             ntrol/WiFiSetup1","eventSubURL":"/upnp/event/WiFiSetup1","SCPDURL":"/setupservic                                                                                                                                                             e.xml"},{"serviceType":"urn:Belkin:service:timesync:1","serviceId":"urn:Belkin:s                                                                                                                                                             erviceId:timesync1","controlURL":"/upnp/control/timesync1","eventSubURL":"/upnp/                                                                                                                                                             event/timesync1","SCPDURL":"/timesyncservice.xml"},{"serviceType":"urn:Belkin:se                                                                                                                                                             rvice:basicevent:1","serviceId":"urn:Belkin:serviceId:basicevent1","controlURL":                                                                                                                                                             "/upnp/control/basicevent1","eventSubURL":"/upnp/event/basicevent1","SCPDURL":"/                                                                                                                                                             eventservice.xml"},{"serviceType":"urn:Belkin:service:firmwareupdate:1","service                                                                                                                                                             Id":"urn:Belkin:serviceId:firmwareupdate1","controlURL":"/upnp/control/firmwareu                                                                                                                                                             pdate1","eventSubURL":"/upnp/event/firmwareupdate1","SCPDURL":"/firmwareupdate.x                                                                                                                                                             ml"},{"serviceType":"urn:Belkin:service:rules:1","serviceId":"urn:Belkin:service                                                                                                                                                             Id:rules1","controlURL":"/upnp/control/rules1","eventSubURL":"/upnp/event/rules1                                                                                                                                                             ","SCPDURL":"/rulesservice.xml"},{"serviceType":"urn:Belkin:service:metainfo:1",                                                                                                                                                             "serviceId":"urn:Belkin:serviceId:metainfo1","controlURL":"/upnp/control/metainf                                                                                                                                                             o1","eventSubURL":"/upnp/event/metainfo1","SCPDURL":"/metainfoservice.xml"},{"se                                                                                                                                                             rviceType":"urn:Belkin:service:remoteaccess:1","serviceId":"urn:Belkin:serviceId                                                                                                                                                             :remoteaccess1","controlURL":"/upnp/control/remoteaccess1","eventSubURL":"/upnp/                                                                                                                                                             event/remoteaccess1","SCPDURL":"/remoteaccess.xml"},{"serviceType":"urn:Belkin:s                                                                                                                                                             ervice:deviceinfo:1","serviceId":"urn:Belkin:serviceId:deviceinfo1","controlURL"                                                                                                                                                             :"/upnp/control/deviceinfo1","eventSubURL":"/upnp/event/deviceinfo1","SCPDURL":"                                                                                                                                                             /deviceinfoservice.xml"},{"serviceType":"urn:Belkin:service:smartsetup:1","servi                                                                                                                                                             ceId":"urn:Belkin:serviceId:smartsetup1","controlURL":"/upnp/control/smartsetup1                                                                                                                                                             ","eventSubURL":"/upnp/event/smartsetup1","SCPDURL":"/smartsetup.xml"},{"service                                                                                                                                                             Type":"urn:Belkin:service:manufacture:1","serviceId":"urn:Belkin:serviceId:manuf                                                                                                                                                             acture1","controlURL":"/upnp/control/manufacture1","eventSubURL":"/upnp/event/ma                                                                                                                                                             nufacture1","SCPDURL":"/manufacture.xml"}]},"presentationURL":"/pluginpres.html"                                                                                                                                                             ,"host":"10.26.100.108","port":"49154","callbackURL":"http://10.26.100.96:36448"                                                                                                                                                             }}} +160ms

[WeMo Platform] Found: WeMo Motion - Master Bedroom, type: sensor

[WeMo Platform] WeMo Motion - Master Bedroom is false

  wemo-client Initial subscription - Device: uuid:Sensor-1_0-221312L1101343, Ser                                                                                                                                                             vice: urn:Belkin:service:basicevent:1 +5ms

[WeMo Platform] Discovered 3 accessories of an unspecified number of accessories                                                                                                                                                             

  wemo-client GetEndDevices Response:  +109ms { 's:Envelope':

   { '$':

      { 'xmlns:s': 'http://schemas.xmlsoap.org/soap/envelope/',

        's:encodingStyle': 'http://schemas.xmlsoap.org/soap/encoding/' },

     's:Body': { 'u:GetEndDevicesResponse': [Object] } } }

  wemo-client endDevices raw data +22ms { '$': { 'xmlns:u': 'urn:Belkin:service:                                                                                                                                                             bridge:1' },

  DeviceLists: '<?xml version="1.0" encoding="utf-8"?><DeviceLists><DeviceList><                                                                                                                                                             DeviceListType>Paired</DeviceListType><DeviceInfos><DeviceInfo><DeviceIndex>2</D                                                                                                                                                             eviceIndex><DeviceID>94103EA2B2787C01</DeviceID><FriendlyName>Guest Toilet</Frie                                                                                                                                                             ndlyName><IconVersion>1</IconVersion><FirmwareVersion>83</FirmwareVersion><Capab                                                                                                                                                             ilityIDs>10006,10008,30008,30009,3000A</CapabilityIDs><CurrentState>0,255:0,,,</                                                                                                                                                             CurrentState><Manufacturer>MRVL</Manufacturer><ModelCode>MZ100</ModelCode><produ                                                                                                                                                             ctName>Lighting</productName><WeMoCertified>YES</WeMoCertified></DeviceInfo></De                                                                                                                                                             viceInfos><GroupInfos><GroupInfo><GroupID>1455368191</GroupID><GroupName>Master                                                                                                                                                              Bedroom</GroupName><GroupCapabilityIDs></GroupCapabilityIDs><GroupCapabilityValu                                                                                                                                                             es></GroupCapabilityValues><DeviceInfos /></GroupInfo><GroupInfo><GroupID>145680                                                                                                                                                             7865</GroupID><GroupName>Master Bedroom</GroupName><GroupCapabilityIDs>10006,100                                                                                                                                                             08,30008,30009,3000A</GroupCapabilityIDs><GroupCapabilityValues>0,255:0,0:0,,</G                                                                                                                                                             roupCapabilityValues><DeviceInfos><DeviceInfo><DeviceIndex>0</DeviceIndex><Devic                                                                                                                                                             eID>94103EA2B27841D1</DeviceID><FriendlyName>Master Bedroom</FriendlyName><IconV                                                                                                                                                             ersion>1</IconVersion><FirmwareVersion>83</FirmwareVersion><CapabilityIDs>10006,                                                                                                                                                             10008,30008,30009,3000A</CapabilityIDs><CurrentState>0,255:0,,,</CurrentState><M                                                                                                                                                             anufacturer>MRVL</Manufacturer><ModelCode>MZ100</ModelCode><productName>Lighting                                                                                                                                                             </productName><WeMoCertified>YES</WeMoCertified></DeviceInfo><DeviceInfo><Device                                                                                                                                                             Index>1</DeviceIndex><DeviceID>94103EA2B2787B5B</DeviceID><FriendlyName>Master B                                                                                                                                                             edroom</FriendlyName><IconVersion>1</IconVersion><FirmwareVersion>83</FirmwareVe                                                                                                                                                             rsion><CapabilityIDs>10006,10008,30008,30009,3000A</CapabilityIDs><CurrentState>                                                                                                                                                             0,255:0,,,</CurrentState><Manufacturer>MRVL</Manufacturer><ModelCode>MZ100</Mode                                                                                                                                                             lCode><productName>Lighting</productName><WeMoCertified>YES</WeMoCertified></Dev                                                                                                                                                             iceInfo></DeviceInfos></GroupInfo></GroupInfos></DeviceList></DeviceLists>\n' }

[WeMo Platform] 3 EndDevices found in:

[WeMo Platform] Found endDevice: Guest Toilet, id: 94103EA2B2787C01

  wemo-client Initial subscription - Device: uuid:Bridge-1_0-231445B01013D0, Ser                                                                                                                                                             vice: urn:Belkin:service:bridge:1 +79ms

[WeMo Platform] Discovered 4 accessories of an unspecified number of accessories                                                                                                                                                             

[WeMo Platform] Found endDevice: Master Bedroom, id: 1455368191

  wemo-client PENDING - returning +12ms

[WeMo Platform] Discovered 5 accessories of an unspecified number of accessories                                                                                                                                                             

[WeMo Platform] Found endDevice: Master Bedroom, id: 1456807865

  wemo-client PENDING - returning +6ms

[WeMo Platform] Discovered 6 accessories of an unspecified number of accessories                                                                                                                                                             

[LiFx] Online: Alodi Lamp [d073d5034e11]

  wemo-client Incoming Request for uuid:Sensor-1_0-221306L110015B: <e:propertyse                                                                                                                                                             t xmlns:e="urn:schemas-upnp-org:event-1-0">

<e:property>

<BinaryState>0</BinaryState>

</e:property>

</e:propertyset>

 

+106ms

[WeMo Platform] WeMo Motion - Passage Way binaryState: off

  wemo-client Incoming Request for uuid:Insight-1_0-221520K12007EB: <e:propertys                                                                                                                                                             et xmlns:e="urn:schemas-upnp-org:event-1-0">

<e:property>

<BinaryState>1|1458034178|5675|8982|8771|1209600|208|205860|95928808|95928808</B                                                                                                                                                             inaryState>

</e:property>

</e:propertyset>

 

+21ms

[WeMo Platform] WeMo Insight binaryState: on

  wemo-client Incoming Request for uuid:Insight-1_0-221520K12007EB: <e:propertys                                                                                                                                                             et xmlns:e="urn:schemas-upnp-org:event-1-0">

<e:property>

<BinaryState>1|1458034178|5675|8982|8771|1209600|208|205860|95928808|95928808</B                                                                                                                                                             inaryState>

</e:property>

</e:propertyset>

 

+9ms

[WeMo Platform] WeMo Insight binaryState: on

  wemo-client GetDeviceStatus Response:  +22ms { 's:Envelope':

   { '$':

      { 'xmlns:s': 'http://schemas.xmlsoap.org/soap/envelope/',

        's:encodingStyle': 'http://schemas.xmlsoap.org/soap/encoding/' },

     's:Body': { 'u:GetDeviceStatusResponse': [Object] } } }

[WeMo Platform] Guest Toilet (bulb) reported as off

[WeMo Platform] Guest Toilet (bulb) reported as at 100% brightness

  wemo-client Incoming Request for uuid:Sensor-1_0-221312L1101343: <e:propertyse                                                                                                                                                             t xmlns:e="urn:schemas-upnp-org:event-1-0">

<e:property>

<BinaryState>0</BinaryState>

</e:property>

</e:propertyset>

 

+35ms

[WeMo Platform] WeMo Motion - Master Bedroom binaryState: off

[LiFx] Online: Craig Lamp [d073d50337ea]

  wemo-client Error on http.request.req: Timed out! +4s

  wemo-client Error on http.request.req: Timed out! +3ms

  wemo-client Error on http.request.req: +223ms { [Error: socket hang up] code:                                                                                                                                                              'ECONNRESET' }

[WeMo Platform] Master Bedroom (bulb) reported as off

[WeMo Platform] Master Bedroom (bulb) reported as at 100% brightness

  wemo-client Error on http.request.req: +6ms { [Error: socket hang up] code: 'E                                                                                                                                                             CONNRESET' }

/usr/local/lib/node_modules/homebridge-platform-wemo/index.js:134

            self.onState = (self._capabilities['10006'].substr(0,1) === '1') ? t                                                                                                                                                             rue : false ;

                                                       ^

 

TypeError: Cannot read property 'substr' of undefined

    at /usr/local/lib/node_modules/homebridge-platform-wemo/index.js:134:56

    at /usr/local/lib/node_modules/homebridge-platform-wemo/index.js:364:21

    at parseResponse (/usr/local/lib/node_modules/homebridge-platform-wemo/node_                                                                                                                                                             modules/wemo-client/client.js:176:21)

    at /usr/local/lib/node_modules/homebridge-platform-wemo/node_modules/wemo-cl                                                                                                                                                             ient/client.js:104:21

    at ClientRequest.<anonymous> (/usr/local/lib/node_modules/homebridge-platfor                                                                                                                                                             m-wemo/node_modules/wemo-client/client.js:77:5)

    at emitOne (events.js:77:13)

    at ClientRequest.emit (events.js:169:7)

    at Socket.socketCloseListener (_http_client.js:235:9)

    at emitOne (events.js:82:20)

    at Socket.emit (events.js:169:7)

    at TCP._onclose (net.js:469:12)

pi@raspberrypi ~ $

**Comment by rudders** [comment]
This is showing that the Master Bedroom bulb is generating TCP errors that should be trapped by the wemo-client I've updated.

can you confirm that if you run
`sudo npm -g ls wemo-client`
you get the following result please.
```
/usr/local/lib
└─┬ homebridge-platform-wemo@0.6.9
  └── wemo-client@0.6.2  (git+https://github.com/rudders/wemo-client.git#1737a652d8e3483463b865614dc9d381304b96ae)
```

**Comment by craigdent** [comment]
Regards,
Craig Dent

**Comment by devbobo** [comment]
This seems to be working correctly for me with my latest code. Please reopen if it's still an issue.

**Comment by alexsalex** [comment]
for me it is still the issue:

events.js:182
      throw er; // Unhandled 'error' event
      ^

TypeError: Cannot read property 'length' of undefined
    at /usr/local/lib/node_modules/homebridge-platform-wemo/index.js:113:49
    at /usr/local/lib/node_modules/homebridge-platform-wemo/node_modules/wemo-client/client.js:163:23
    at Parser.<anonymous> (/usr/local/lib/node_modules/homebridge-platform-wemo/node_modules/xml2js/lib/xml2js.js:493:18)
    at emitOne (events.js:115:13)
    at Parser.emit (events.js:210:7)
    at SAXParser.onerror (/usr/local/lib/node_modules/homebridge-platform-wemo/node_modules/xml2js/lib/xml2js.js:311:26)
    at emit (/usr/local/lib/node_modules/homebridge-platform-wemo/node_modules/sax/lib/sax.js:624:35)
    at error (/usr/local/lib/node_modules/homebridge-platform-wemo/node_modules/sax/lib/sax.js:653:5)
    at strictFail (/usr/local/lib/node_modules/homebridge-platform-wemo/node_modules/sax/lib/sax.js:677:7)
    at beginWhiteSpace (/usr/local/lib/node_modules/homebridge-platform-wemo/node_modules/sax/lib/sax.js:951:7)
    at SAXParser.write (/usr/local/lib/node_modules/homebridge-platform-wemo/node_modules/sax/lib/sax.js:1006:11)
    at Parser.exports.Parser.Parser.parseString (/usr/local/lib/node_modules/homebridge-platform-wemo/node_modules/xml2js/lib/xml2js.js:508:31)
    at Parser.parseString (/usr/local/lib/node_modules/homebridge-platform-wemo/node_modules/xml2js/lib/xml2js.js:7:59)
    at Object.exports.parseString (/usr/local/lib/node_modules/homebridge-platform-wemo/node_modules/xml2js/lib/xml2js.js:540:19)
    at parseResponse (/usr/local/lib/node_modules/homebridge-platform-wemo/node_modules/wemo-client/client.js:162:12)
    at module.exports.<anonymous> (/usr/local/lib/node_modules/homebridge-platform-wemo/node_modules/wemo-client/client.js:121:5)
root@MS:/var/lib/homebridge# sudo npm -g ls homebridge-platform-wemo
/usr/local/lib
└── homebridge-platform-wemo@1.3.1
